export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECT_CATEGORY = "GET_PROJECT_CATEGORY";
export const GET_PRODUCT_NEW = "GET_PRODUCT_NEW";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";